version: '3.0'
services:
  backend:
    build: ./backend
    container_name: dashboard_backend
    image: dashboard_backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: dashboard_db
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_data: