version: '3.9'

services:
  flask_app:
    container_name: flask_app
    image: flask_img
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@flask_db:5432/postgres
    depends_on:
      - flask_db
  
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - pgdata:${PG_DATA}
  
volumes:
  pgdata: {}
    
