# Generated by Django 5.0.6 on 2024-07-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_project_manager_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('uncompleted', 'Uncompleted')], max_length=12, null=True),
        ),
    ]
