# Generated by Django 5.0.6 on 2024-06-20 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('age', models.PositiveIntegerField(unique=True)),
                ('position', models.CharField(max_length=40)),
                ('hire_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
